# Generated by Django 3.1.7 on 2021-08-05 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Task', '0002_auto_20210805_1932'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userform',
            name='mobile_Number',
            field=models.CharField(max_length=15),
        ),
    ]
